### ISSUE TITLE
Game crash on firmware 16.1 for moment

### ISSUE THREAD

**Issue by calimero6201** [ZenoArrows/The-Simpsons-Hit-and-Run#12]
Game crash after click on new game on firmware 16.1, i reboot on atmosphere

**Comment by impeeza** [comment]
Nop, I am on firmware 16.1.0, Atmosphère 1.05.0, Hekate 6.0.7 and works fine.

**Comment by ZenoArrows** [comment]
Yeah works fine for me too, might be a different issue. Try to make sure you're using the english PC installation files.

**Comment by calimero6201** [comment]
Thanks it’s ok now, great works 🙂💪

**Comment by impeeza** [comment]
Confirmed work, so this issue can be closed?
