### ISSUE TITLE
Convert.bat File No Work 

### ISSUE THREAD

**Issue by KittyBua** [ZenoArrows/The-Simpsons-Hit-and-Run#13]
convert.bat File No Work

**Comment by KittyBua** [comment]
Here Finish File Torrent thanks Telegramm bot

https://www.filesharesite.com/files/202310/1697202538290E615272C8CFD461F62B5534E4A6A3.html

**Comment by impeeza** [comment]
convert worked for me, thanks a lot for the link

**Comment by KittyBua** [comment]
No Problem 😃 thanks my friend

**Comment by KittyBua** [comment]
Work
