### ISSUE TITLE
Begining of mission #3 - Black screen file not found

### ISSUE THREAD

**Issue by jckfun** [ZenoArrows/The-Simpsons-Hit-and-Run#17]
Thanks for your awesome work. 

I love this game. 

Blocking issue. When I start mission 3, after talking to Ned Flander’s (omer’s neightbour), I have a black screen saying :
FileNotFound : cooler.p3d

I use version 0.1

any idea ?

Thanks

**Comment by ZenoArrows** [comment]
That file should be in `art\frontend\dynaload\images\msnicons\object\cooler.p3d`, have you checked if it copied over correctly?

Also make sure you didn't format the SD card as exFAT, the Switch is notorious for corrupting exFAT filesystems.

**Comment by jckfun** [comment]
Thanks for your answer ZenoArrows.

I have a 1 TB micro SD card and I have formated the card in FTA32 using HEKATE.

I will have a look for that file.

Maybe the issue is coming for the fact that I downloaded a ready to use archive.

I may have to build my own pack using the ISO file of the game.

Regards,

**Comment by jckfun** [comment]
I think the issue was coming from the fact that I copied pasted from a MAC. So some corrupted file. I did the same from a PC. Works fine. Sorry for the inconvenience and congratulations for your work. Regards,
