### ISSUE TITLE
Level 4 (Marge) ERROR AUDIO AND DIALOGS SPANISH

### ISSUE THREAD

**Issue by GamerCarl** [ZenoArrows/The-Simpsons-Hit-and-Run#19]
Hello, I have a problem in level 4 of Marge, the audio in Spanish is bugged and nothing can be heard, only the music of the game but from there the horn, voices, dialogues, etc. do not work. I saw another post that also reported the same thing. Furthermore, since there is no dialogue, the characters are left talking forever.

**Comment by ZenoArrows** [comment]
Known issue, level 4 is bugged currently unfortunately. Working on it.

**Comment by ZenoArrows** [comment]
Duplicate of #9
