### ISSUE TITLE
Button controls reversed in settings display

### ISSUE THREAD

**Issue by hippydave** [ZenoArrows/The-Simpsons-Hit-and-Run#2]
Nice job on the port! Just got the movies converted and got it up and running.

In settings from the pre game menu (Homer on the sofa), the controls display shows X & Y reversed, and A & B reversed, compared to what they do in game.

**Comment by ZenoArrows** [comment]
You're right, those are in the original configuration before I changed it to match the tutorial (and switch games in general). This just requires an update to frontend.p3d, I'll update that no actual code changes required.

**Comment by hippydave** [comment]
Awesome, thanks!

**Comment by ZenoArrows** [comment]
Swapped around the text now, just re-download the zip and extract it into the installation folder on your switch.
