### ISSUE TITLE
Crash on bootup

### ISSUE THREAD

**Issue by Abecker1111** [ZenoArrows/The-Simpsons-Hit-and-Run#26]
it says file “not” and the error code is 
(c2-12828-1) Also this code 
Psp2core-1699275546-0x000005254b-ebook.bin.psp2dmp

**Comment by ZenoArrows** [comment]
Please give the error in the description

**Comment by DigiD2** [comment]
Did you FTP the files over? That was the issue for me.  This has also happened before with a game or two. I was running into " _stubs" folder issue transfering. Even when zipped and unzipped on vita directly,it unzipped fine but was giving errors and could not be deleted unless plugged directly into pc. 

What fixes it(least every time for me) was transfering directly via a card reader plugged into pc or plug in the sd card to your computer card reader slot directly. Im assuming you can just connect your vita via usb and do it that way too. Just dont do it wirelessly and do it directly.

**Comment by Abecker1111** [comment]
Ima try I did use FTB

**Comment by Abecker1111** [comment]
I couldn’t figure out how to do it on my Mac I tried for mad long

**Comment by ZenoArrows** [comment]
Please keep pre-alpha Vita issues in ticket #11, currently not really tracking issue reports for it until the port is more complete.
