### ISSUE TITLE
Crash on the first spash screen

### ISSUE THREAD

**Issue by Kiappo142** [ZenoArrows/The-Simpsons-Hit-and-Run#27]
The game doesn’t go past the first screen, giving me the error C2-12828-1. Tried multiple times to reinstall the game and replacing the files but all the efforts give the same result. Core file: psp2core-1699280813-0x0000122767-eboot.bin.psp2dmp

**Comment by ZenoArrows** [comment]
Please keep pre-alpha Vita issues in the ticket #11
