### ISSUE TITLE
When traveling on foot, the camera is inverted

### ISSUE THREAD

**Issue by devffy** [ZenoArrows/The-Simpsons-Hit-and-Run#3]
When moving on foot, the camera is inverted (if you press the stick to the left, the camera rotates to the left), but in the car everything works fine (if you press the stick to the left, the camera rotates to the right).

**Comment by ZenoArrows** [comment]
This appears to be intentional, though the original console versions did have an option to invert the horizontal camera controls. I'll see if I can re-introduce that option in a future version.

**Comment by hippydave** [comment]
Maybe things like this and language setting could be controlled from an ini file if you didn't want to have to add stuff to in-game menus.

**Comment by ITotalJustice** [comment]
i agree with the above. you could use a ini to remap the controls as well

example for ps2 layout + camera inverted
```ini
[controls]
a = b
b = y
x = a
y = x
camera_invert = true
```

**Comment by k1x92** [comment]
Any fix allready? tested someone to edit ini? config?

when yes, how to do?

**Comment by nunokalhau** [comment]
found this

https://old.reddit.com/r/SteamDeck/comments/14ihds3/the_simpsons_hit_run_native_pc_port_setup_details/jpls3lu/

but the controller settings are gone after starting the game, so I'm assuming this isn't being used to read the settings from?

**Comment by k1x92** [comment]
Something new for 0.4 Version maybe? I think this issue is one of the biggest right now....

**Comment by k1x92** [comment]
What i was thinking overnight is, when there is no fix eta, maybe someone can do a "cheat file" with edizon to fix it.
theoretically it should work, in zelda there are also cheats for movement speed, Infinite jumping... 

Change some hax, for the invert movement while running

**Comment by k1x92** [comment]
@ZenoArrows you think you fix it in 0.5? Any ideas?

**Comment by hippydave** [comment]
> @ZenoArrows you think you fix it in 0.5? Any ideas?

He's said he'll look at this stuff once the obvious bugs have been fixed, please try to be patient.

**Comment by k1x92** [comment]
@ZenoArrows 

No new Update this weekend?

**Comment by k1x92** [comment]
@ZenoArrows any update?

**Comment by hippydave** [comment]
> @ZenoArrows any update?

Dude stop, just wait.

**Comment by k1x92** [comment]
> > @ZenoArrows any update?
> 
> Dude stop, just wait.

Why are you talking about this?

Again two weeks no update.. 

I understand you are on vita Version right now, but why when its f*ckd, no one plays vita anymore, switch Versions runs good so far, just Focus on switch and make it dope (just some tweaks movement may the widescreen hud ui and stuff) and this Problem is since begining and its shit with the invert movement...

**Comment by k1x92** [comment]
And look just on Youtube/Reddit.. so many ppl wants this, and wait to play until its fixed/implimated

**Comment by ZenoArrows** [comment]
@k1x92 If people wait to play until this is implemented, then that's a good thing. There are still plenty of serious bugs that negatively impact the experience and I'd want people to enjoy the port when it's completed.

Developing the Vita and Switch ports concurrently is not slowing stuff down, in fact having more platforms to test on helps with troubleshooting bugs. And hey, doing a port like this is about having fun and attempting to run the port on the Vita is my definition of fun, it doesn't really matter if anyone is still using it.

**Comment by k1x92** [comment]
@ZenoArrows will 0.5 happen?

**Comment by ZenoArrows** [comment]
@k1x92 No, it won't ever happen: https://github.com/ZenoArrows/The-Simpsons-Hit-and-Run/releases/tag/v0.5
