### ISSUE TITLE
Crash on Switch FW 18.1.0

### ISSUE THREAD

**Issue by impeeza** [ZenoArrows/The-Simpsons-Hit-and-Run#47]
Hello there,

The software worked fine until I upgraded to Firmware 18.0.0.

Today I am using Atmosphère 1.7.2, FW 18.1.0 and the game loads until the first splash, then crash.

I think you need to build using latest LIBNX.

regards.

**Comment by impeeza** [comment]
For me on Firmware 18.1.0 (rebootless update), Atmosphère 1.7.1, latest sigpatches and SYS-Patch Sysmodule

The most recent release 0.6.1 (18f9b4e)  (https://github.com/ZenoArrows/The-Simpsons-Hit-and-Run/releases/tag/v0.6.1)  the game loads fine.

Thanks @ZenoArrows for all your effort, clossing the issue.

**Comment by samus123456** [comment]
User error. The issue was incorrect movie files being used.

**Comment by impeeza** [comment]
OK,  a Layer 8 error  :P  


yes the movies format changed between 0.3 and 0.4 versions so you have to follow the most recent installation instructions.

**Comment by samus123456** [comment]
My problem was trying to use an install that changed the opening movie files to make them tiny. The 0.4 I had came with ones that worked.
