### ISSUE TITLE
are you going to port simpsons the game to switch?

### ISSUE THREAD

**Issue by kingcocacola** [ZenoArrows/The-Simpsons-Hit-and-Run#59]
are you going to port simpsons the game to switch?

**Comment by Pullup59** [comment]
Did you seriously make an account for Ask that ? If I was you I would delete that, you don't imagine how much you can upset someone with thing like this.
Are you gonna pay him ? Have you even consider thanking him ?
Thank's Zeno for this work 🙏 I Hope one day I will have you're level in dev

**Comment by ZenoArrows** [comment]
It already ported to the Switch.
