### ISSUE TITLE
Movie Playback?

### ISSUE THREAD

**Issue by MotoLegacy** [ZenoArrows/The-Simpsons-Hit-and-Run#62]
0.6.1 PS Vita

I've seen some comments online suggesting PS Vita is now able to play RAD movies without conversion, but I haven't been able to see this in action myself. I can also find [YouTube videos such as this one](https://www.youtube.com/watch?v=SBh2i6aUAz8) that demonstrate this functioning. Is this a problem with my game data, or am I misinformed that conversion is no longer necessary?

**Comment by MotoLegacy** [comment]
Closing, this was an error on my part. I did a clean rip from my CDs and it works correctly now.

**Comment by godz-dot** [comment]
hey, what is going on in the game?

**Comment by godz-dot** [comment]
![Uploading images.jpeg…]()
