### ISSUE TITLE
Level 4 movie ends prematurely

### ISSUE THREAD

**Issue by MotoLegacy** [ZenoArrows/The-Simpsons-Hit-and-Run#64]
Tested on 0.6.1 PS Vita

Playback of the Level 4 movie ends before the actual EOF.

To reproduce:
1. Load Save with Level 4 Movie unlocked
2. Play Level 4 Movie through Main Menu options
3. Observe premature end

**Comment by P0liak** [comment]
Couldn't reproduce, I could share a proof of it in a short clip tho if you want

**Comment by MotoLegacy** [comment]
No need, thanks for the feedback. Could I get the md5 hash for your level 4 movie? So I can compare and check if mine is broken. That would be great!

**Comment by P0liak** [comment]
File: Main Storage/Download/movies/movies/fmv4.rmv
MD5: 627178c9a68d71a2336c0592b35d0607

**Comment by P0liak** [comment]
Tested on 0.6.1 ntsc, maybe the bug happens with pal languages, didn't ask which one you've used

**Comment by MotoLegacy** [comment]
Thanks for providing the hash, I confirmed there was a problem with the actual file and it plays fine now (am on NTSC, to answer the region question). Closing.
