### ISSUE TITLE
Xbox Widescreen FMVs

### ISSUE THREAD

**Issue by mmcgr97** [ZenoArrows/The-Simpsons-Hit-and-Run#66]
Does anyone know how I can use the widescreen FMVs from the xbox version of the game instead of the 4:3 ones from the PC version?

**Comment by ZenoArrows** [comment]
There are no widescreen FMVs, the Xbox version just cuts off the top and bottom to make it fit. Like this:

![image](https://github.com/user-attachments/assets/38aa3055-64d7-487d-b734-3d2ec6bb6aef)
