### ISSUE TITLE
Crash on 18.1.0/1.7.1 - v0.61

### ISSUE THREAD

**Issue by k1x92** [ZenoArrows/The-Simpsons-Hit-and-Run#71]
With 0.5 everything works, but when i replace with 0.61 i get Atmosphere Crash 010000000000100D.
PAL german
any idea?

**Comment by k1x92** [comment]
![IMG_1457](https://github.com/user-attachments/assets/e3d40974-ba43-4995-b57f-471048df1524)

**Comment by k1x92** [comment]
@ZenoArrows?

**Comment by ZenoArrows** [comment]
010000000000100D is the title id of the Album applet, which means you are trying to run homebrew from an applet. Running homebrew from an applet will rarely work because it can only access a few hundred MB of RAM rather than the several GBs of RAM that a regular switch title can access.
