### ISSUE TITLE
Level 4 (Marge) audio issues

### ISSUE THREAD

**Issue by f00god** [ZenoArrows/The-Simpsons-Hit-and-Run#9]
Level 4 (Marge) is having audio issues. All voice lines are missing. Civil transport has no sound.

**Comment by ZenoArrows** [comment]
Which mission does this happen in?

**Comment by ZenoArrows** [comment]
I can't reproduce it, it works fine for me. Are you using the french audio language files?

**Comment by f00god** [comment]
english

**Comment by f00god** [comment]
I tried another PC build today. Problem still exists.

Tried the new 0.2 patch and updated my Firmware from 15.0.1 to 16.1.

**Comment by ZenoArrows** [comment]
I've reproduced this issue, it only happens on the switch though. Seems to be related to issue #16.

**Comment by ZenoArrows** [comment]
Should be fixed in version 0.4

**Comment by ZenoArrows** [comment]
> I've reproduced this issue, it only happens on the switch though. Seems to be related to issue #16.

Small correction to this, the reason I could only reproduce it on Switch was because I was running Release configuration builds on it while running Debug configuration builds on my PC. The issue was reproducible on both platforms in the Release configuration.
